import Dashboard from "../../imges/Svg File/Dashboard";
import Emergncy from "../../imges/Svg File/Emergncy";
import Eyeicon from "../../imges/Svg File/Eyeicon";
import ProfileIcon from "../../imges/Svg File/ProfileIcon";
import Treatment from "../../imges/Svg File/Treatment";
import Usericon from "../../imges/Svg File/Usericon";

export const countries = [
  {
    code: "US",
    name: "English",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
  },
  {
    code: "GB",
    name: "Spain",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
  },
  {
    code: "IN",
    name: "Hindi",
    flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
  },
  // Add more countries as needed...
];

export const notifications = [
  {
    id: 1,
    title: "Notification 1",
    message:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    title: "Notification 2",
    message:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
  },
];

export const patients = [
  {
    id: 1,
    name: "Patient 1",
    phone: "+48 58798624",
    gender: "Male",
    age: 30,
    avatarUrl: require("../../imges/profileImg.png"),
    fullname: "Robert Smith",
    email: "robertsmith@gmail.com",
    address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
  },
  {
    id: 2,
    name: "Patient 2",
    phone: "+48 58798624",
    gender: "Female",
    age: 31,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 3,
    name: "Patient 3",
    phone: "+48 58798624",
    gender: "Male",
    age: 32,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 4,
    name: "Patient 4",
    phone: "+48 58798624",
    gender: "Female",
    age: 33,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 5,
    name: "Patient 5",
    phone: "+48 58798624",
    gender: "male",
    age: 34,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 6,
    name: "Patient 6",
    phone: "+48 58798624",
    gender: "Female",
    age: 35,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 7,
    name: "Patient 7",
    phone: "+48 58798624",
    gender: "male",
    age: 36,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 8,
    name: "Patient 8",
    phone: "+48 58798624",
    gender: "Female",
    age: 37,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 9,
    name: "Patient 9",
    phone: "+48 58798624",
    gender: "male",
    age: 38,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 10,
    name: "Patient 10",
    phone: "+48 58798624",
    gender: "Female",
    age: 39,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 11,
    name: "Patient 11",
    phone: "+48 58798624",
    gender: "male",
    age: 40,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 12,
    name: "Patient 12",
    phone: "+48 58798624",
    gender: "Female",
    age: 41,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 13,
    name: "Patient 13",
    phone: "+48 58798624",
    gender: "male",
    age: 42,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 14,
    name: "Patient 14",
    phone: "+48 58798624",
    gender: "female",
    age: 43,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 15,
    name: "Patient 15",
    phone: "+48 58798624",
    gender: "male",
    age: 44,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 16,
    name: "Patient 16",
    phone: "+48 58798624",
    gender: "female",
    age: 45,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 17,
    name: "Patient 17",
    phone: "+48 58798624",
    gender: "male",
    age: 46,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 18,
    name: "Patient 18",
    phone: "+48 58798624",
    gender: "female",
    age: 47,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 19,
    name: "Patient 19",
    phone: "+48 58798624",
    gender: "male",
    age: 48,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 20,
    name: "Patient 20",
    phone: "+48 58798624",
    gender: "female",
    age: 49,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 21,
    name: "Patient 21",
    phone: "+48 58798624",
    gender: "male",
    age: 30,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 22,
    name: "Patient 22",
    phone: "+48 58798624",
    gender: "female",
    age: 31,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 23,
    name: "Patient 23",
    phone: "+48 58798624",
    gender: "male",
    age: 32,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 24,
    name: "Patient 24",
    phone: "+48 58798624",
    gender: "female",
    age: 33,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 25,
    name: "Patient 25",
    phone: "+48 58798624",
    gender: "male",
    age: 34,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 26,
    name: "Patient 26",
    phone: "+48 58798624",
    gender: "Female",
    age: 35,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 27,
    name: "Patient 27",
    phone: "+48 58798624",
    gender: "male",
    age: 36,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 28,
    name: "Patient 28",
    phone: "+48 58798624",
    gender: "Female",
    age: 37,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 29,
    name: "Patient 29",
    phone: "+48 58798624",
    gender: "male",
    age: 38,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 30,
    name: "Patient 30",
    phone: "+48 58798624",
    gender: "Female",
    age: 39,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 31,
    name: "Patient 31",
    phone: "+48 58798624",
    gender: "male",
    age: 40,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 32,
    name: "Patient 32",
    phone: "+48 58798624",
    gender: "Female",
    age: 41,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 33,
    name: "Patient 33",
    phone: "+48 58798624",
    gender: "male",
    age: 42,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 34,
    name: "Patient 34",
    phone: "+48 58798624",
    gender: "Female",
    age: 43,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 35,
    name: "Patient 35",
    phone: "+48 58798624",
    gender: "male",
    age: 44,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 36,
    name: "Patient 36",
    phone: "+48 58798624",
    gender: "Female",
    age: 45,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 37,
    name: "Patient 37",
    phone: "+48 58798624",
    gender: "male",
    age: 46,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 38,
    name: "Patient 38",
    phone: "+48 58798624",
    gender: "Female",
    age: 47,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 39,
    name: "Patient 39",
    phone: "+48 58798624",
    gender: "male",
    age: 48,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 40,
    name: "Patient 40",
    phone: "+48 58798624",
    gender: "Female",
    age: 49,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 41,
    name: "Patient 41",
    phone: "+48 58798624",
    gender: "male",
    age: 30,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 42,
    name: "Patient 42",
    phone: "+48 58798624",
    gender: "Female",
    age: 30,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 43,
    name: "Patient 43",
    phone: "+48 58798624",
    gender: "male",
    age: 31,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 44,
    name: "Patient 44",
    phone: "+48 58798624",
    gender: "Female",
    age: 32,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 45,
    name: "Patient 45",
    phone: "+48 58798624",
    gender: "male",
    age: 33,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 46,
    name: "Patient 46",
    phone: "+48 58798624",
    gender: "Female",
    age: 34,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 47,
    name: "Patient 47",
    phone: "+48 58798624",
    gender: "male",
    age: 35,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 48,
    name: "Patient 48",
    phone: "+48 58798624",
    gender: "Female",
    age: 36,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 49,
    name: "Patient 49",
    phone: "+48 58798624",
    gender: "male",
    age: 37,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 50,
    name: "Patient 50",
    phone: "+48 58798624",
    gender: "Female",
    age: 38,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 51,
    name: "Patient 51",
    phone: "+48 58798624",
    gender: "male",
    age: 39,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 52,
    name: "Patient 52",
    phone: "+48 58798624",
    gender: "Female",
    age: 40,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 53,
    name: "Patient 53",
    phone: "+48 58798624",
    gender: "male",
    age: 41,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 54,
    name: "Patient 54",
    phone: "+48 58798624",
    gender: "Female",
    age: 42,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 55,
    name: "Patient 55",
    phone: "+48 58798624",
    gender: "male",
    age: 43,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 56,
    name: "Patient 56",
    phone: "+48 58798624",
    gender: "Female",
    age: 44,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 57,
    name: "Patient 57",
    phone: "+48 58798624",
    gender: "male",
    age: 45,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 58,
    name: "Patient 58",
    phone: "+48 58798624",
    gender: "Female",
    age: 46,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 59,
    name: "Patient 59",
    phone: "+48 58798624",
    gender: "male",
    age: 47,
    avatarUrl: require("../../imges/profileImg.png"),
  },

  {
    id: 60,
    name: "Patient 60",
    phone: "+48 58798624",
    gender: "Female",
    age: 48,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 61,
    name: "Patient 61",
    phone: "+48 58798624",
    gender: "male",
    age: 49,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 62,
    name: "Patient 62",
    phone: "+48 58798624",
    gender: "Female",
    age: 30,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 63,
    name: "Patient 63",
    phone: "+48 58798624",
    gender: "male",
    age: 31,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 64,
    name: "Patient 64",
    phone: "+48 58798624",
    gender: "Female",
    age: 32,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 65,
    name: "Patient 65",
    phone: "+48 58798624",
    gender: "male",
    age: 33,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 66,
    name: "Patient 66",
    phone: "+48 58798624",
    gender: "Female",
    age: 34,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 67,
    name: "Patient 67",
    phone: "+48 58798624",
    gender: "male",
    age: 35,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 68,
    name: "Patient 68",
    phone: "+48 58798624",
    gender: "Female",
    age: 36,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 69,
    name: "Patient 69",
    phone: "+48 58798624",
    gender: "male",
    age: 37,
    avatarUrl: require("../../imges/profileImg.png"),
  },

  {
    id: 70,
    name: "Patient 70",
    phone: "+48 58798624",
    gender: "Female",
    age: 38,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 71,
    name: "Patient 71",
    phone: "+48 58798624",
    gender: "male",
    age: 39,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 72,
    name: "Patient 72",
    phone: "+48 58798624",
    gender: "Female",
    age: 40,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 73,
    name: "Patient 73",
    phone: "+48 58798624",
    gender: "male",
    age: 41,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 74,
    name: "Patient 74",
    phone: "+48 58798624",
    gender: "Female",
    age: 42,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 75,
    name: "Patient 75",
    phone: "+48 58798624",
    gender: "male",
    age: 43,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 76,
    name: "Patient 76",
    phone: "+48 58798624",
    gender: "Female",
    age: 44,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 77,
    name: "Patient 77",
    phone: "+48 58798624",
    gender: "male",
    age: 45,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 78,
    name: "Patient 78",
    phone: "+48 58798624",
    gender: "Female",
    age: 46,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 79,
    name: "Patient 79",
    phone: "+48 58798624",
    gender: "male",
    age: 47,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 80,
    name: "Patient 80",
    phone: "+48 58798624",
    gender: "Female",
    age: 48,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 81,
    name: "Patient 81",
    phone: "+48 58798624",
    gender: "male",
    age: 49,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 82,
    name: "Patient 82",
    phone: "+48 58798624",
    gender: "Female",
    age: 30,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 83,
    name: "Patient 83",
    phone: "+48 58798624",
    gender: "male",
    age: 31,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 84,
    name: "Patient 84",
    phone: "+48 58798624",
    gender: "Female",
    age: 32,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 85,
    name: "Patient 85",
    phone: "+48 58798624",
    gender: "male",
    age: 33,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 86,
    name: "Patient 86",
    phone: "+48 58798624",
    gender: "Female",
    age: 34,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 87,
    name: "Patient 87",
    phone: "+48 58798624",
    gender: "male",
    age: 35,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 88,
    name: "Patient 88",
    phone: "+48 58798624",
    gender: "Female",
    age: 36,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 89,
    name: "Patient 89",
    phone: "+48 58798624",
    gender: "male",
    age: 37,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 90,
    name: "Patient 90",
    phone: "+48 58798624",
    gender: "Female",
    age: 38,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 91,
    name: "Patient 91",
    phone: "+48 58798624",
    gender: "male",
    age: 40,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 92,
    name: "Patient 92",
    phone: "+48 58798624",
    gender: "Female",
    age: 41,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 93,
    name: "Patient 93",
    phone: "+48 58798624",
    gender: "male",
    age: 42,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 94,
    name: "Patient 94",
    phone: "+48 58798624",
    gender: "Female",
    age: 43,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 95,
    name: "Patient 95",
    phone: "+48 58798624",
    gender: "male",
    age: 44,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 96,
    name: "Patient 96",
    phone: "+48 58798624",
    gender: "Female",
    age: 45,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 97,
    name: "Patient 97",
    phone: "+48 58798624",
    gender: "male",
    age: 46,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 98,
    name: "Patient 98",
    phone: "+48 58798624",
    gender: "Female",
    age: 47,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 99,
    name: "Patient 99",
    phone: "+48 58798624",
    gender: "male",
    age: 48,
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 100,
    name: "Patient 100",
    phone: "+48 58798624",
    gender: "Female",
    age: 49,
    avatarUrl: require("../../imges/profileImg.png"),
  },
];

export const Runningdata = [
  {
    id: 1,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 2,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },

  {
    id: 3,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },

  {
    id: 4,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },

  {
    id: 5,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },

  {
    id: 6,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },

  {
    id: 7,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 8,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },
  {
    id: 9,
    title: "Completion 35,36",
    name: "Dianne Russell",
    date: "02 Sep, 2024",
    avatarUrl: require("../../imges/profileImg.png"),
  },
];

// export const userlist = [
//   {
//     id: 1,
//     name: "Dianne Russell",
//     date: "02 Sep, 2024",
//     imgSrc: <Eyeicon></Eyeicon>,
//   },
//   {
//     id: 2,
//     name: "Dianne Russell",
//     date: "02 Sep, 2024",
//     imgSrc: <Eyeicon></Eyeicon>,
//   },
//   {
//     id: 3,
//     name: "Dianne Russell",
//     date: "02 Sep, 2024",
//     imgSrc: <Eyeicon></Eyeicon>,
//   },
//   {
//     id: 4,
//     name: "Dianne Russell",
//     date: "02 Sep, 2024",
//     imgSrc: <Eyeicon></Eyeicon>,
//   },
//   {
//     id: 5,
//     name: "Dianne Russell",
//     date: "02 Sep, 2024",
//     imgSrc: <Eyeicon></Eyeicon>,
//   },
//   {
//     id: 6,
//     name: "Dianne Russell",
//     date: "02 Sep, 2024",
//     imgSrc: <Eyeicon></Eyeicon>,
//   },

// ];

